var title1 = [
  "The Truth of",
  "Research on",
  "Research on",
  "The fundamental concepts of",
  "The Texture of",
  "Facts and fiction of",
  "Concise Information of",
  "The Implications of",
  "Rules for Mastering",
  "How and Why of",
  "The Connections Between Life and",
  "The importance of",
  "Fundamentals of",
  "The Core Principles of",
  "Intertwined Relationships Between Agnoiology and",
  "A Revolution in",
  "The Hyperparameters of",
  "Electrolysis, Self Mutation and",
  "Obdormition, Xerosis and",
  "Anthropobiological Evidence of",
  "Kinesiological Evidence of",
  "Pharmacoenvironmentological Evidence of",
  "",
  "",
  "",
  ""
];
var conj1 = [//普通連接詞，要加逗號
  "In other words",
  "To put it more simply",
  "Conversely",  
  "Alternatively",
  "On the contrary",
  "On the other hand",
  "Most important of all",
  "Most fundamental of all",
  "Therefore",
  "However",
  "Having said that",
  "By contrast",
  "Thus",
  "For this reason",
  "As expressed",
  "Undoubtedly",
  "Unquestionably",
  "Definitely",
  "Certainly",
  "Apparently",
  "Obviously",
  "In comparison",
  "In addition",
  "Furthermore",
  "Besides",
  "In fact",
  "Similarly",
  "Notably",
  "Notwithstanding",
  "In any case",
  "Under those circumstances"

];
var conj2 = [//序數，要加逗號
  ["First","Firstly","The First","In the first place","To begin with","To start with", "First and foremost"],
  ["Second","Secondly","The second","In the second place"],
  ["Third","Thirdly","The Third","In the third place"],
  ["Moreover","Furthermore","In addition","Then","Next", "Besides","Further more","What's more","Not to mention"],
  ["Last but not least","Finally","Last","The last"]
];
var conj3 = [//結尾，不加逗號
  "This suggests that",
  "It can get seen that",
  "The consequence is",
  "This supports the idea that",
  "This proves that",
  "There is no doubt that"
];
var conj4 = [//結尾
  "In other words",
  "To put it more simply",
  "Conversely",  
  "Resulting",
  "Most important of all",
  "Therefore",
  "By contrast",
  "Thus",
  "As a result",
  "Overall",
  "Lastly",
  "For this reason",
  "As expressed",
  "Undoubtedly",
  "Unquestionably",
  "Definitely",
  "Certainly",
  "To conclude",
  "To sum up",
  "In summary",
  "Apparently",
  "Obviously",
  "Given these points",
  "Hence",
  "Consequently",
  "In short",
  "In summary"
];
var conj5 = [//不加逗號
  "Another key thing to remember is",
  "I believe that",
  "It could seem that",
  "It could be argued that",
  "As recent statatics shows",
  "Over the years of evolution"

];
var conj6 = [//開頭，加逗號
  "To begin with",
  "To start with",
  "As a start",
  "As mentioned in the previous dissertation",
  "First things come first",
  "As mentioned",
  "At the outset",
  "Incipiently",
  "First and foremost",
  "In the first place",
  "",
  ""
];
var quote1 = [
  ["The greatest glory in living lies not in never falling, but in rising every time we fall",
  "The way to get started is to quit talking and begin doing",
  "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking",
  "If life were predictable it would cease to be life, and be without flavor",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success",
  "Life is what happens when you're busy making other plans",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier",
  "When you reach the end of your rope, tie a knot in it and hang on",
  "Always remember that you are absolutely unique. Just like everyone else",
  "Don't judge each day by the harvest you reap but by the seeds that you plant",
  "The future belongs to those who believe in the beauty of their dreams",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn",
  "The best and most beautiful things in the world cannot get seen or even touched - they must be felt with the heart",
  "It is during our darkest moments that we must focus to see the light",
  "Whoever is happy will make others happy too",
  "Do not go where the path may lead, go instead where there is no path and leave a trail",
  "You will face many defeats in life, but never let yourself be defeated",
  "The greatest glory in living lies not in never falling, but in rising every time we fall",
  "In the end, it's not the years in your life that count. It's the life in your years",
  "Never let the fear of striking out keep you from playing the game",
  "Life is either a daring adventure or nothing at all",
  "Many of life's failures are people who did not realize how close they were to success when they gave up",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose",
  "Success covers a multitude of blunders",
  "All that glitters is not gold",
  "A rose by any other name would smell as sweet",
  "All that glitters is not gold",
  "A nation's culture resides in the hearts and in the soul of its people",
  "Live as if you were to die tomorrow. Learn as if you were to live forever",
  "Old habits die hard",
  "You cannot shake hands with a clenched fist",
  "There is nothing permanent except change",
  "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward"
  ],
  ["Nelson Mandela",
  "Walt Disney",
  "Steve Jobs",
  "Eleanor Roosevelt",
  "Oprah Winfrey",
  "James Cameron",
  "John Lennon",
  "Mother Teresa",
  "Franklin D. Roosevelt",
  "Margaret Mead",
  "Robert Louis Stevenson",
  "Eleanor Roosevelt",
  "Benjamin Franklin",
  "Helen Keller",
  "Aristotle",
  "Anne Frank",
  "Ralph Waldo Emerson",
  "Maya Angelou",
  "Nelson Mandela",
  "Abraham Lincoln",
  "Babe Ruth",
  "Helen Keller",
  "Thomas A. Edison",
  "Dr. Seuss",
  "George Bernard Shaw",
  "William Shakespeare",
  "William Shakespeare",
  "Maxwell",
  "Joziah Farren",
  "Jason Wu",
  "Nelson Mandnela",
  "Indira Gandhi",
  "Heraclitus",
  "Amelia Earhart"
  ]
];
//search words
const PHYSICS = 'scienceelectromagnetmotionenergyengineeringaerodynamicsquantumphysicsthermodynamicswavesparticlesouterspaceuniverseatomsforce';
const CHEMISTRY = 'chemistryengineeringparticlesmoleculesatomschemicalrecationgibbs';
const MATH = 'mathamaticsequationvectorgeometryalgebrasequencesumproductdivisionsubtractionmultiplicationcountangledegreelinecirclesquare'
const BIOLOGY = 'biologyanimalplantmicrobesmicroscopecoronavirusbacteriafungusdnacellcatdogelephanttigerlionleopardantbeemosquitobearbutterflyinsectbeetleorganismsleaftreeflowerhippo';
const HUMAN = 'brainarmlegfeethandtoefingernailfacemoutheyenosethroatlunglivergutkidneystomachelbowkneeskinhairlimbichippocampustonguelipchestpancreasintestinesbone';
const SCIENCE = MATH + PHYSICS + CHEMISTRY;
const MEDICATION = BIOLOGY + HUMAN;
var sen1 = [//keywords between
  ["Scientists all over the world have tried to create a formula for",", but it is harder than thought", SCIENCE],
  ["Such as time and space are intertwined,"," is inseperable from humanity and technology", PHYSICS],
  [" I have been thinking of the mechanisms of","for days and nights, but it still confuses me a lot every once in a while", SCIENCE],
  ["In this era of technological giants, "," is undoubtedly one variable that we couldn't ignore", SCIENCE],
  ["While more and more scientists have devoted themselves into exploring",", they have only lifted a corner of the great veil", SCIENCE],
  ["As the population of","grows exponentially, we don't know how it would affect modern human life", BIOLOGY],
  ["Since the genetic materials of","has been decoded recently, we can now get better insights about its natural behaviors", BIOLOGY],
  ["Devastating as it seems, the sudden rise of","population has infected people all around the world", BIOLOGY],
  ["Although the deadly","has raised a potential to collapse modern medical resources, doctors worldwide have collectively put a new treatment under numorous clinical trials",MEDICATION],
  /*["By pondering for days and nights, I finally figured out the true meaning of",""],*/
  ["A lot of people seem to think that","is what we always think about in our daily lives"],
  ["The world would have an enormous change if","disappears from our planet"],
  ["If we aren't fully aware of",", what will happen goes without saying"],
  ["What we know about","is only the tip of the iceberg, only through harder study and more research can we find out the real concept of this issue"],
  ["According to a huge amount of research,  the true meaning of","is as clear as a bell"],
  ["Researchers from different fields of knowledge tried to analyze",", but many of them failed"],
  ["A huge group of scientists tried to figure out the texture of","for decades, but they didn't figure it out until now"],
  ["","is such an interesting field of knowledge that we can explore"],
  /*["I cannot imagine a world without",""],*/
  ["The existence of","changed the world dramatically"],
  ["The world needs improvement, so we need a deeper understanding of",""],
  ["If you handle the primary thinking process, then you can take control of",""],
  /*["","would become the standard of the future world"],*/
  ["","is not only an important issue, but it might also change one's life"],
  ["As","gains popularity worldwide, many economic giants are willing to invest in this area of knowledge"],
  ["Recently, the problem of","has bought us into focus"],
  ["Nowadays,","has become a problem we have to face"],
  ["","has been playing an increasingly significant role in our day-to-day life. It has brought a lot of benefits but has created some serious problems as well"],
  ["It is universally acknowledged that","has had a great impact on our daily lives"],
  ["In a word, the whole society should pay close attention to the problem of",", only in this way, the world can thrive rapidly in the future"],
  ["With the rapid development of science and technology, more and more people believe that","has changed the world dramatically", SCIENCE]
];
var sen2 = [//after a quote
  "This quote made me think in a higher level",
  "This is profoundly meaningful to me, so thought-provoking that made me improve myself",
  "It's absolutely true, the meaning of the proverb made me think of the meaning of life",
  "Whenever I hear someone say that, I would feel the same",
  "Hearing people say it makes me feel the warmth of human society",
  "When hearing this saying, I feel the same way as they do",
  "I have thought about this problem for decades",
  "By thinking for days and nights, I finally figured out the true meaning of this quote",
  "It makes me ponder days and nights everytime I hear this proverb being said",
  "This concept takes me to a higher level in life",
  "This concept seems complicated to the mind, but the logic of it is as clear as a bell",
  "I highly recommend those who has the same problem as I do read this quote carefully, it might lead us to a higher level of conseption and understanding",
  "Ever since I've heard this saying, I felt like being encouraged and have the strength to power up my future",
  "For once and forever, this quote stroke my heartstrings, making me more confident in facing new challenges"
];
var sen3 = [//pure bullshit
  "This concept takes us to a higher level, making me want to think of it twice",
  "As far as our rapidly advancing technology takes us, we should go over this problem seriously and have full awareness of its potential dangers",
  "The answer is abundantly clear, but we might have a hard time comprehending the true meaning of it. Besides, the moral behind the answer is also what we should devote lots of time to researching",
  /*"Thinking about it for days and nights tired me",*/
  "By doing lots of research, we finally found out the answer",
  "What we think is not the truth of the real thing, we should have more evidence to make this momentous decision",
  "We should think twice to make an accurate definition of this issue",
  "We should take this problem seriously and always be aware of what happens",
  "Having an optimistic mind increases the chances of solving this problem",
  "Keeping your mind clear is extremely helpful for solving this problem",
  "The root of this problem is not complicated, we should think again before giving up",
  "This situation is not rare; therefore, by thinking twice, you might find a better solution",
  "This concept seems complicated to the mind, but the logic of it is as clear as a bell",
  "The answer to this issue might not get seen by the naked eye, but by devoting our lives to think about it, I'm sure the result would be clear",
  "When you have problems solving this issue, the solution might be just beside you",
  "As far as I am concerned, I agree with the latter opinion to some extent"
];
var sen4 = [//conclusion
  ["","has a great impact on our daily lives"],
  ["The world would have an enormous change if","disappears from our planet"],
  ["","is such an unrivaled field of knowledge that we can explore"],
  ["The most fundamental thing is that we found out the core concept of",""],
  ["By knowing what","certainly is, we have made ourselves more competitive in this age of knowledge explosion"],
  ["In this era of technological giants, "," is surely one variable that we couldn't ignore"],
  ["With the rapid development of science and technology, more and more people believe that","has changed the world dramatically"],
  ["The whole society should pay close attention to the problem of",", only in this way, the world can thrive rapidly in the future"]
];

